name: Python CI

on:
  push:
    branches:
      - main
      - cezar
      - vigenere
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m py_compile *.py
